Validate cmd images
projectcontour/contour-operator pull request #149
Opened 2020-12-02 23:16 UTC by danehans

Validates `contour-image` and `envoy-image` command-line flags.

Fixes: https://github.com/projectcontour/contour-operator/issues/41

2020-12-08 00:11 UTC, Miciah commented
You need to import hash algorithms to support digests:
```go
import (
	// ...

	_ "crypto/sha256"
	_ "crypto/sha512"

	// ...
)
```
I noticed this issue when I tried using a SHA512 digest (`<image>@sha256:<hash>`).  See <https://github.com/opencontainers/go-digest#usage>.  (I wonder if `github.com/docker/distribution/reference` has any other little surprises.)

2020-12-09 20:42 UTC, danehans commented
Commit `10db8c9` resolves https://github.com/projectcontour/contour-operator/pull/149#issuecomment-740259360.

2020-12-09 23:17 UTC, Miciah commented
/lgtm

2020-12-15 21:33 UTC, skriss approved these changes
LGTM

2020-12-16 05:21 UTC, jpeach requested changes

2020-12-16 05:21 UTC, jpeach commented on cmd/contour-operator.go
> +	_ "crypto/sha512"
Please comment why this is needed

2020-12-16 05:21 UTC, jpeach commented on cmd/contour-operator.go
> +			setupLog.Error(err, "invalid image reference", "value", image)
While we are touching this, let's make `setupLog` local, since it doesn't need to be a global var.

2020-12-16 05:21 UTC, jpeach commented on cmd/contour-operator.go
> +		_, err := reference.Parse(image)
Consider wrapping `reference.Parse` and adding a test to defend against the fragility that @Miciah pointed out.

2020-12-16 19:41 UTC, danehans commented
@jpeach commit `8ccfb9e` resolves your feedback above, PTAL.

2020-12-17 15:52 UTC, stevesloka approved these changes
/lgtm

2020-12-17 15:52 UTC, merged