Adds Readme Update to Release Script
projectcontour/contour-operator pull request #167
Opened 2020-12-17 20:15 UTC by danehans

Updates the release script to update versioned links in `README.md`.

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2021-01-13 20:51 UTC, stevesloka requested changes
For me when testing, the `$NEWVERS` doesn't get applied correctly. Example:

```
-$ kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour-operator/main/examples/operator/operator.yaml
+$ kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour-operator/v1.99.99/examples/operator/operator.yaml

```

2021-01-13 20:53 UTC, stevesloka commented on hack/release/make-release-tag.sh
>  readonly OLDVERS="$1"
Move this up before the other variables introduced.

2021-01-26 19:22 UTC, skriss requested changes
Looks good apart from @stevesloka's comment about moving `OLDVERS` and `NEWVERS` up to the top of the var list.

2021-01-29 17:33 UTC, skriss approved these changes
LGTM

2021-01-29 17:43 UTC, stevesloka approved these changes

2021-01-29 17:44 UTC, merged