Adds Route Selection Validation for Gateway
projectcontour/contour-operator pull request #226
Opened 2021-02-26 01:49 UTC by danehans

- Adds route selection validation for the Gateway API type.
- Adds unit tests for Gateway and GatewayClass validation logic.

Fixes: https://github.com/projectcontour/contour-operator/issues/215

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2021-03-02 18:35 UTC, danehans commented
fixes: https://github.com/projectcontour/contour-operator/issues/234

2021-03-18 14:59 UTC, skriss requested changes

2021-03-18 14:59 UTC, skriss commented on pkg/slice/slice.go
> +	}
I think if you change L42 to just `var newSlice []gatewayv1alpha1.Listener` then you don't need this.

2021-03-18 14:59 UTC, skriss commented on pkg/validation/validation.go
> +		}
I don't think I see a test case for this block, would be nice to add one

2021-03-18 17:23 UTC, danehans commented
@skriss thanks for the review. Commit `5eef417` resolves your above comments.

2021-03-18 17:27 UTC, danehans commented on go.mod
> +replace github.com/projectcontour/contour => github.com/danehans/contour v0.13.0-beta.2.0.20210318163459-9274cd62d96d
xref: https://github.com/projectcontour/contour-operator/issues/266

2021-03-26 16:13 UTC, danehans commented
/hold until Gateway API [implementation plan](https://docs.google.com/document/d/1kOrGqHXULYO6YLxGCOtVyjz_7mfcW7Yi1WXCpQz6_Qo/edit?usp=sharing) is resolved.

2021-03-30 05:35 UTC, danehans commented
xref https://github.com/kubernetes-sigs/gateway-api/pull/597 to add validation pkg upstream.

2021-05-25 16:06 UTC, sunjayBhatia reviewed
seems like this is on hold, just sending a review to clear it out of my queue, please re-request if this needs it again

2021-06-09 19:06 UTC, danehans commented
Closing since GatewayClass and Gateway controllers are being migrated to Contour.

2021-06-09 19:06 UTC, closed without merging