Conditionally Starts Gateway Controllers
projectcontour/contour-operator pull request #261
Opened 2021-03-14 01:00 UTC by danehans

Adds gateway/gatewayclass controllers if the operator is started with the gateway flag (defaults to true). Note that the operator will fail to start if the necessary Gateway CRDs are not installed int the cluster.

Fixes #221 

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2021-03-17 06:28 UTC, youngnick requested changes
LGTM overall, with the exception of the defaulting behavior.

Defaulting the gateway flag to true when that can make the operator terminate immediately (if the Gateway APIs objects aren't installed) feels a bit weird.

In the controller, we're planning on having "are the Gateway objects installed" be the trigger for if the informers are registered; does it make more sense to check that and just enable the informers if the CRDs are present? In this case, I think the informers would not be used unless you have a GatewayClass, per our previous discussions.

If not, and we want to go with an explicit flag, it seems like it should probably be false by default. I think autodetect is a better option, but whatever we do needs to consider that we want people to be able to use the operator *without* having it shut down on install because you didn't install the Gateway CRDs yet.

2021-03-17 16:13 UTC, stevesloka requested changes
The flag should probably be the name/namespace of the gateway? 

I think a hard crash of the operator feels bad since other instances may not be using gatewayapi?

//ref: https://github.com/projectcontour/contour/issues/3377

2021-03-23 01:12 UTC, danehans commented
@stevesloka @youngnick thanks for the review. Commit `fc597e5` resolves your comments above and implements a logger for the operator, PTAL.

2021-03-23 02:58 UTC, youngnick commented
> The flag should probably be the name/namespace of the gateway?
Because the operator can handle multiple instances of Contour, the flag we pass to it can't be the name and namespace of the gateway, that has to come from the Contour object.

This change should just enable watching the APIs, then it's up to the Contour object being linked to a GatewayClass and Gateway to say if the Gateway APIs should be used or not.

2021-03-23 03:00 UTC, youngnick approved these changes
LGTM, I think this is just what we need.

2021-03-23 04:28 UTC, danehans commented on internal/operator/operator.go
> +	for i, crd := range crds {
@youngnick good point. I created https://github.com/projectcontour/contour-operator/issues/270 to reduce the API calls in a future PR.

2021-03-23 04:31 UTC, danehans commented
https://github.com/projectcontour/contour-operator/pull/248 is required for CI to pass.

2021-03-23 18:07 UTC, stevesloka reviewed
Just to be clear @danehans there's no flag to configure? The only key is against the existence of the gateway-apis?

2021-03-25 16:03 UTC, danehans commented
@stevesloka yes, that's correct. I apologize for causing any confusion by not updating the PR description. The description is now updated to accurately reflect the changes.

2021-03-30 15:15 UTC, skriss commented
@stevesloka leaving this one for you to put the stamp of approval on

2021-03-30 16:10 UTC, danehans commented
@stevesloka I'm impartial to moving this PR forward. If we proceed with [your Gateway API implementation plan](https://docs.google.com/document/d/1kOrGqHXULYO6YLxGCOtVyjz_7mfcW7Yi1WXCpQz6_Qo/edit?usp=sharing), then this PR is unneeded.

2021-03-30 16:18 UTC, stevesloka approved these changes
@danehans my proposal is going nowhere with the team so will just merge and move along.

2021-03-30 16:18 UTC, merged