Updates RBAC for TCP/UDPRoute Types
projectcontour/contour-operator pull request #304
Opened 2021-04-15 22:15 UTC by danehans

Updates RBAC to support TCPRoute and UDPRoute types.

Fixes #303

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2021-04-15 23:53 UTC, skriss approved these changes

2021-04-16 01:24 UTC, nak3 approved these changes

2021-04-16 17:26 UTC, stevesloka requested changes

2021-04-16 17:26 UTC, stevesloka commented on internal/operator/operator.go
> +// +kubebuilder:rbac:groups=networking.x-k8s.io,resources=udproutes/status;tcproutes/status,verbs=update
nit: Can we just combine these with the previous rules to make the output in the same sections? With it this way, tcproutes & udp routes get their own RBAC sections.

2021-04-16 17:49 UTC, stevesloka approved these changes
I'm going to merge this to fixup `:main` and can follow up with other PRs to fix up the permissions in this file in future PRs.

2021-04-16 17:49 UTC, merged