Improves Gateway Validation
projectcontour/contour-operator pull request #349
Opened 2021-05-04 03:12 UTC by danehans

-`internal/operator/controller/gateway/controller.go`: Moves validation before checking finalizer of gateway (provides consistency with other controllers). `EnsureGateway` now takes a `Contour` as a parameter since contour<>gateway validation is now fully handled by the validation pkg.
- `pkg/validation/validation.go`: Adds `gatewayContour()` used to validate the contour<>gateway association. Adds a check to ensure `contour.spec.namespace.name` = `gateway.namespace`.
 
Fixes #344 

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2021-05-04 08:59 UTC, nak3 reviewed
LGTM! Thank you

2021-05-04 08:59 UTC, nak3 commented on pkg/validation/validation.go
> +		return nil, fmt.Errorf("failed to get contour for gateway %s/%s", gw.Namespace, gw.Name)
```suggestion
		return nil, fmt.Errorf("failed to get contour for gateway %s/%s: %w", gw.Namespace, gw.Name, err)
```

I think `ContourForGateway()`'s err gives us useful information when failed.

2021-05-04 08:59 UTC, nak3 commented on pkg/validation/validation.go
> +		return nil, fmt.Errorf("invalid contour.spec.namespace.name for gateway %s/%s", gw.Namespace, gw.Name)
```suggestion
		return nil, fmt.Errorf("invalid contour.spec.namespace.name for gateway %s/%s, it must be the same namespace as the Gateway", gw.Namespace, gw.Name)
```
I think it should be clarified why it was invalid.

2021-05-04 17:01 UTC, danehans commented
@nak3 thanks for the review. Commit `e38d751` resolves your comments above.

2021-05-04 17:43 UTC, danehans commented
CI failing due to https://github.com/projectcontour/contour-operator/issues/341.

2021-05-06 10:52 UTC, nak3 commented
/lgtm

2021-05-06 18:44 UTC, skriss requested changes
one godoc nit but otherwise LGTM

2021-05-06 18:44 UTC, skriss commented on pkg/validation/validation.go
>  // Gateway returns an error if gw is an invalid Gateway.
let's update the godoc to indicate this now returns the Contour associated with the Gateway, if the Gateway is valid.

2021-05-07 17:53 UTC, sunjayBhatia reviewed
content looks good, pending @skriss' comment

is there a test we can write to ensure this behavior? unit or otherwise?

2021-05-10 17:42 UTC, sunjayBhatia commented
> @skriss commit `0d3be78` updates the `Gateway()` godocs.
> 
> > is there a test we can write to ensure this behavior? unit or otherwise?
> 
> @sunjayBhatia we would need an e2e tests since the Gateway validation function uses the controller-runtime client for portions of the validation. Since an invalid gateway is reflected as an error-level log message and not in status, we would need to re-add the log scraping and check for :
> 
> `2021-05-10T10:16:02.027-0700 ERROR controller-runtime.manager.controller.gateway_controller Reconciler error {"name": "test-gateway", "namespace": "knative-serving", "error": "failed to validate gateway knative-serving/test-gateway: failed to validate contour for gateway knative-serving/test-gateway: invalid contour namespace \"contour-external\"; namespace must match gateway namespace \"knative-serving\""}`
> 
> I intended to refactor the controller to pass invalidity to the status sync, but I have not proceeded with this due to the gateway re-implementation plan.

could we take advantage of the fake client controller runtime provides for testing? https://pkg.go.dev/github.com/kubernetes-sigs/controller-runtime/pkg/client/fake

2021-05-10 21:41 UTC, danehans commented
@sunjayBhatia xref https://github.com/projectcontour/contour/pull/3659 for re-implementing gateway/gatewayclass controllers in contour.

2021-05-17 14:57 UTC, skriss commented
needs an update for the example/e2e matrix, sorry @danehans

2021-05-19 18:20 UTC, danehans commented
@sunjayBhatia thanks for the reference to the fake client. Commit `48ad370` adds gateway validation unit tests and refactors listener validation to be consistent with [upstream](https://github.com/kubernetes-sigs/gateway-api/blob/v0.3.0/apis/v1alpha1/validation/validation.go#L58-L85).

2021-05-21 15:13 UTC, sunjayBhatia reviewed
some overlap with the existing contour changes around TLSRoute/protocol etc. and some test comments

2021-05-21 15:13 UTC, sunjayBhatia commented on pkg/validation/validation_test.go
> +		"invalid number of gateway listeners": {
i think this might be allowed now by Contour itself cc @stevesloka

2021-05-21 15:13 UTC, sunjayBhatia commented on pkg/validation/validation_test.go
> +							Protocol: gatewayv1alpha1.TLSProtocolType,
i think this is allowed by Contour itself now, see https://github.com/projectcontour/contour/commit/72edf8beb1ebbc5dc17319b92b15fc474c85de30

2021-05-21 15:13 UTC, sunjayBhatia commented on pkg/validation/validation_test.go
> +			_, err := validation.Gateway(context.TODO(), cl, tc.gw)
should we also test the expected contour resource is returned?

2021-05-21 15:13 UTC, sunjayBhatia commented on pkg/validation/validation.go
> +	if contour.Spec.Namespace.Name != gw.Namespace {
do we have a test case that covers this check?

2021-05-25 05:09 UTC, danehans commented
@sunjayBhatia thanks for the review. Commit `56e1dc3` resolves your comments above.

2021-05-25 15:58 UTC, sunjayBhatia commented on pkg/validation/validation_test.go
> +		"invalid listener, tls protocol without config": {
i think this might be legal right now in Contour since we're not terminating TLS with TLSRoute and just doing passthrough for now cc @stevesloka

2021-05-25 15:58 UTC, sunjayBhatia commented on pkg/validation/validation_test.go
> +		"invalid listener, tls protocol without config": {
though it is a little counter to the described spec

2021-05-25 15:59 UTC, sunjayBhatia commented
overall looks good to me, just gotta get the tests passing and work out the TLS protocol required TLS secret etc. or not

2021-05-25 16:52 UTC, danehans commented
> overall looks good to me, just gotta get the tests passing and work out the TLS protocol required TLS secret etc. or not

@sunjayBhatia I think it's best to keep the validation updates in this PR focused on the referenced bug. I prefer to spend the time getting the validation checks upstream than expanding the checks here.

2021-05-25 17:03 UTC, sunjayBhatia commented
> > overall looks good to me, just gotta get the tests passing and work out the TLS protocol required TLS secret etc. or not
> 
> @sunjayBhatia I think it's best to keep the validation updates in this PR focused on the referenced bug. I prefer to spend the time getting the validation checks upstream than expanding the checks here.

makes sense its just that the operator via this change might be adding a constraint to the gateway that contour does not, but its not a big issue tbh

2021-05-25 17:03 UTC, sunjayBhatia approved these changes

2021-05-26 16:17 UTC, merged